import type { FramePoseResult, JointAngles, NormalizedPoint } from "../../types/ai-analysis";
const valid = (p?: NormalizedPoint): p is NormalizedPoint => Boolean(p && Number.isFinite(p.x) && Number.isFinite(p.y));
const round = (value: number) => Math.round(value * 10) / 10;
export function calculateJointAngle(a: NormalizedPoint, b: NormalizedPoint, c: NormalizedPoint): number | undefined { if (!valid(a)||!valid(b)||!valid(c)) return; const bax=a.x-b.x,bay=a.y-b.y,baz=(a.z??0)-(b.z??0),bcx=c.x-b.x,bcy=c.y-b.y,bcz=(c.z??0)-(b.z??0); const ba=Math.hypot(bax,bay,baz),bc=Math.hypot(bcx,bcy,bcz); if(!ba||!bc)return; const cosine=Math.min(1,Math.max(-1,(bax*bcx+bay*bcy+baz*bcz)/(ba*bc))); return round(Math.acos(cosine)*180/Math.PI); }
export function calculateTorsoInclination(p: NormalizedPoint[]): number | undefined { const [sl,sr,hl,hr]=[p[11],p[12],p[23],p[24]]; if(![sl,sr,hl,hr].every(valid))return; const sx=(sl.x+sr.x)/2,sy=(sl.y+sr.y)/2,hx=(hl.x+hr.x)/2,hy=(hl.y+hr.y)/2; return round(Math.abs(Math.atan2(sx-hx,hy-sy)*180/Math.PI)); }
export function calculateShoulderAlignment(p: NormalizedPoint[]): number | undefined { const l=p[11],r=p[12]; return valid(l)&&valid(r)?round(Math.abs(Math.atan2(r.y-l.y,r.x-l.x)*180/Math.PI)):undefined; }
export function calculatePoseConfidence(p: NormalizedPoint[]): number { const v=p.map(x=>x.visibility).filter((x):x is number=>Number.isFinite(x)); return v.length?round(v.reduce((a,b)=>a+b,0)/v.length):0; }
export function calculatePoseSymmetry(a: JointAngles): number | undefined { const pairs=[[a.leftElbow,a.rightElbow],[a.leftKnee,a.rightKnee],[a.leftHip,a.rightHip]]; const d=pairs.filter((x):x is number[]=>x[0]!==undefined&&x[1]!==undefined).map(x=>Math.abs(x[0]-x[1])); return d.length?round(Math.max(0,100-d.reduce((x,y)=>x+y,0)/d.length*2)):undefined; }
export function calculateFrameJointAngles(p: NormalizedPoint[]): JointAngles { return {leftElbow:calculateJointAngle(p[11],p[13],p[15]),rightElbow:calculateJointAngle(p[12],p[14],p[16]),leftKnee:calculateJointAngle(p[23],p[25],p[27]),rightKnee:calculateJointAngle(p[24],p[26],p[28]),leftHip:calculateJointAngle(p[11],p[23],p[25]),rightHip:calculateJointAngle(p[12],p[24],p[26]),torsoInclination:calculateTorsoInclination(p),shoulderAlignment:calculateShoulderAlignment(p)}; }
export const reduceFrameResultsForStorage=(frames:FramePoseResult[]):FramePoseResult[]=>frames.map(({timestamp,detected,confidence,jointAngles})=>({timestamp,detected,confidence,jointAngles}));
