import { useMemo, useState, type CSSProperties } from "react";
import {
  Activity, ArrowRight, Bell, CalendarDays, ChevronDown, CloudUpload, FileText,
  Gauge, LayoutDashboard, LockKeyhole, LogOut, Mail, Menu, Moon, Play, Search,
  Settings, Share2, Sparkles, Trophy, Upload, Users, Video, Wind, X, Zap,
  UserRound, ShieldCheck, Building2, CheckCircle2, Eye, BarChart3, BrainCircuit
} from "lucide-react";
import NavFlowBrand from "./components/NavFlowBrand";
import NavFlowAIAnalyzer from "./components/video/NavFlowAIAnalyzer";

const nav = [
  [LayoutDashboard, "Tableau de bord"], [Video, "Analyses"], [Play, "Vidéos"],
  [Users, "Athlètes"], [Activity, "Progression"], [Trophy, "Compétitions"],
  [Gauge, "Comparaisons"], [Zap, "Exercices"], [CalendarDays, "Calendrier"],
  [FileText, "Rapports"], [Sparkles, "IA Coach"],
] as const;

type Analysis = { name: string; boat: string; score: number; date: string };
const initialAnalyses: Analysis[] = [
  { name: "Virement de bord", boat: "ILCA 7", score: 89, date: "Aujourd’hui" },
  { name: "Départ", boat: "Optimist", score: 82, date: "Hier" },
  { name: "Empannage", boat: "ILCA 6", score: 91, date: "18/07/2026" },
  { name: "Près", boat: "ILCA 7", score: 84, date: "15/07/2026" },
  { name: "Vent arrière", boat: "ILCA 7", score: 78, date: "14/07/2026" },
];

const stats = [
  [Video, "Analyses réalisées", "148", "+18% cette semaine", "blue"],
  [Gauge, "Score technique moyen", "87/100", "Excellent", "green"],
  [Activity, "Temps analysé", "32 h", "+5.6 h cette semaine", "violet"],
  [Users, "Athlètes suivis", "26", "+3 nouveaux", "orange"],
  [Upload, "Vidéos importées", "214", "+24 cette semaine", "cyan"],
  [Sparkles, "Progression IA", "+12%", "Ce mois-ci", "teal"],
] as const;

function ScoreRing({ score = 88 }: { score?: number }) {
  return <div className="score-ring" style={{ "--score": `${score * 3.6}deg` } as CSSProperties}><div><b>{score}</b><span>/100</span></div></div>;
}

function LineChart() {
  const points = "0,118 40,88 80,76 120,50 160,67 200,44 240,74 280,49 320,38 360,48 400,34 440,21";
  return <svg viewBox="0 0 440 140" className="chart">{[20,60,100,140].map(y=><line key={y} x1="0" x2="440" y1={y} y2={y}/>)}<polyline className="chart-fill" points={`0,140 ${points} 440,140`}/><polyline className="chart-line" points={points}/>{points.split(" ").map((p,i)=>{const[x,y]=p.split(",");return <circle key={i} cx={x} cy={y} r="4"/>})}</svg>;
}

function Landing({ onLogin }: { onLogin: () => void }) {
  return <div className="landing">
    <header className="landing-nav"><NavFlowBrand/><nav><a href="#features">Fonctionnalités</a><a href="#disciplines">Disciplines</a><a href="#experience">Solutions</a><a href="#footer">Ressources</a></nav><div><button className="text-button" onClick={onLogin}>Se connecter</button><button className="landing-cta" onClick={onLogin}>Essayer gratuitement</button></div></header>
    <section className="hero"><div className="hero-copy"><span className="eyebrow"><Sparkles/> L’IA au service de la performance nautique</span><h1>Analysez chaque mouvement.<br/><em>Naviguez plus vite.</em></h1><p>SailMotion AI transforme vos vidéos de voile en données techniques claires : posture, stabilité, vitesse et recommandations personnalisées.</p><div className="hero-actions"><button className="landing-cta" onClick={onLogin}>Analyser une vidéo <ArrowRight/></button><button className="outline-button" onClick={()=>document.getElementById("features")?.scrollIntoView({behavior:"smooth"})}><Play/> Découvrir la plateforme</button></div><div className="hero-proof"><b>148+</b><span>analyses réalisées</span><b>87/100</b><span>score moyen</span><b>26</b><span>athlètes suivis</span></div></div><div className="hero-visual"><img src="/sailing/laser.jpg" alt="Voilier ILCA analysé par SailMotion AI"/><div className="floating-score"><ScoreRing score={92}/><span>Performance globale</span></div><div className="floating-data"><Wind/><span><b>18 nds</b> Vent moyen</span></div></div></section>
    <section className="mobile-value"><div><Video/><span>Analyse vidéo IA</span></div><div><Gauge/><span>Comparaison référence</span></div><div><BarChart3/><span>Suivi de progression</span></div></section>
    <section id="disciplines" className="disciplines"><div className="section-heading"><div><span className="eyebrow">TOUTES LES DISCIPLINES</span><h2>Une seule plateforme.</h2></div><p>Adaptée à chaque type de bateau et à chaque niveau.</p></div><div className="boat-grid">{[["ILCA 7 / 6 / 4","/sailing/laser.jpg"],["OPTIMIST","/sailing/catamaran.jpg"],["CATAMARAN","/sailing/catamaran.jpg"],["420","/sailing/laser.jpg"],["470","/sailing/laser.jpg"],["NACRA 15","/sailing/catamaran.jpg"]].map(([name,img])=><article key={name}><img src={img}/><b>{name}</b></article>)}</div></section>
    <section id="features" className="feature-section"><span className="eyebrow">PLATEFORME COMPLÈTE</span><h2>Tout ce qu’il faut pour progresser</h2><div>{[[Video,"Analyse vidéo IA","Détection de posture et lecture image par image."],[FileText,"Rapports intelligents","Rapports détaillés et conseils personnalisés."],[Gauge,"Comparaison","Comparez vos performances avec vos références."],[BrainCircuit,"Coach IA personnel","Conseils instantanés et plan d’entraînement."],[Activity,"Progression continue","Suivez vos progrès dans le temps."],[CloudUpload,"Accessible partout","Vos données sécurisées dans le cloud."]].map(([Icon,title,text])=><article key={String(title)}><span><Icon/></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section id="experience" className="experience"><div className="section-heading"><div><span className="eyebrow">EXPÉRIENCE COMPLÈTE</span><h2>Conçue pour les athlètes et les coachs.</h2></div></div><div>{[["Analyse vidéo","/sailing/laser.jpg"],["Comparaison","/sailing/catamaran.jpg"],["Tableau de bord","/sailing/laser.jpg"],["Rapport IA","/sailing/catamaran.jpg"]].map(([title,img],i)=><article key={title}><div><img src={img}/><span>{i===0?<Play/>:i===1?<Users/>:i===2?<BarChart3/>:<FileText/>}</span></div><h3>{title}</h3><p>{["Lisez, analysez et segmentez chaque mouvement.","Comprenez vos différences et progressez plus vite.","Toutes vos données clés au même endroit.","Exportez et partagez vos analyses."][i]}</p></article>)}</div></section>
    <section className="landing-stats">{[["2500+","Athlètes"],["120+","Clubs"],["18 000+","Vidéos analysées"],["50+","Compétitions suivies"],["98%","Précision IA"]].map(([v,l])=><div key={l}><b>{v}</b><span>{l}</span></div>)}</section>
    <section className="final-cta"><img src="/sailing/catamaran.jpg"/><div><h2>Prêt à faire passer vos performances<br/>au niveau supérieur ?</h2><p>Rejoignez SailMotion AI et commencez votre première analyse.</p></div><button className="landing-cta" onClick={onLogin}>Commencer gratuitement <ArrowRight/></button></section>
    <footer id="footer" className="landing-footer"><div className="footer-brand"><NavFlowBrand compact/><p>La plateforme d’analyse vidéo IA dédiée à la voile.</p></div><div className="footer-links"><div><b>Plateforme</b><a href="#features">Fonctionnalités</a><a href="#disciplines">Disciplines</a><a href="#experience">Solutions</a></div><div><b>Ressources</b><a href="#footer">Guides</a><a href="#footer">Tutoriels</a><a href="#footer">FAQ</a></div></div><div className="developer-signature"><span>Developed by</span><img src="/brand/mouad-logo.png" alt="Logo Mouad Mouasseif"/><strong>Mouad Mouasseif</strong></div><div className="footer-bottom"><span>© 2026 SailMotion AI. Tous droits réservés.</span><span>Confidentialité · Conditions d’utilisation</span></div></footer>
  </div>;
}

function Login({ onSubmit, onBack }: { onSubmit: () => void; onBack: () => void }) {
  const [step,setStep]=useState<"profile"|"login"|"signup"|"forgot"|"verify">("profile");
  if(step==="profile")return <div className="auth-shell profile-choice"><button className="auth-back" onClick={onBack}>←</button><NavFlowBrand/><div className="auth-heading"><span>Bienvenue sur</span><h1>SailMotion <em>AI</em></h1><p>Choisissez votre profil pour commencer</p></div><div className="profile-options">{[[UserRound,"Athlète","Suivre mes analyses et ma progression","cyan"],[ShieldCheck,"Coach","Gérer et entraîner mes athlètes","green"],[Building2,"Admin / Club","Gérer mon club, mes coachs et mes athlètes","violet"]].map(([Icon,title,text,color])=><button key={String(title)} onClick={()=>setStep("login")} className={String(color)}><Icon/><span><b>{title}</b><small>{text}</small></span><ArrowRight/></button>)}</div><p className="auth-switch">Vous avez déjà un compte ? <button onClick={()=>setStep("login")}>Se connecter</button></p></div>;
  if(step==="forgot")return <div className="auth-shell auth-centered"><button className="auth-back" onClick={()=>setStep("login")}>←</button><span className="auth-symbol"><Mail/></span><h1>Mot de passe oublié ?</h1><p>Entrez votre adresse email et nous vous enverrons un lien pour réinitialiser votre mot de passe.</p><label className="auth-field"><Mail/><input type="email" placeholder="Adresse email"/></label><button className="login-submit" onClick={()=>setStep("verify")}>Envoyer le lien</button><button className="link-button" onClick={()=>setStep("login")}>Retour à la connexion</button></div>;
  if(step==="verify")return <div className="auth-shell auth-centered"><button className="auth-back" onClick={()=>setStep("forgot")}>←</button><span className="auth-symbol"><CheckCircle2/></span><h1>Vérifiez votre email</h1><p>Nous avons envoyé un code à <b>coach@sailmotion.ai</b></p><div className="verify-code">{[2,4,8,6,1,3].map((n,i)=><span key={i}>{n}</span>)}</div><p>Renvoyer le code dans <b>00:45</b></p><button className="login-submit" onClick={onSubmit}>Vérifier le code</button><button className="link-button" onClick={()=>setStep("forgot")}>Changer d’adresse email</button></div>;
  if(step==="signup")return <form className="auth-shell auth-form" onSubmit={e=>{e.preventDefault();onSubmit()}}><button type="button" className="auth-back" onClick={()=>setStep("login")}>←</button><h1>Créer un compte</h1><p>Rejoignez SailMotion AI</p><label className="auth-field"><UserRound/><input required placeholder="Nom complet"/></label><label className="auth-field"><Mail/><input required type="email" placeholder="Adresse email"/></label><label className="auth-field"><LockKeyhole/><input required type="password" placeholder="Mot de passe"/></label><label className="auth-field"><LockKeyhole/><input required type="password" placeholder="Confirmer le mot de passe"/></label><label className="terms"><input required type="checkbox"/> J’accepte les Conditions d’utilisation et la Politique de confidentialité</label><button className="login-submit">Créer mon compte</button><p className="auth-switch">Vous avez déjà un compte ? <button type="button" onClick={()=>setStep("login")}>Se connecter</button></p></form>;
  return <div className="login-page"><div className="login-photo"><img src="/sailing/catamaran.jpg" alt="Équipe de voile"/><button onClick={onBack}>← Retour à l’accueil</button><div><NavFlowBrand/><h2>Votre prochaine progression commence ici.</h2><p>Analyse technique et coaching vidéo dans une seule plateforme.</p></div></div><form className="login-card auth-form" onSubmit={e=>{e.preventDefault();onSubmit()}}><button type="button" className="auth-back mobile-only" onClick={()=>setStep("profile")}>←</button><NavFlowBrand compact/><span className="eyebrow">ESPACE COACH</span><h1>Se connecter</h1><p>Accédez à votre espace SailMotion AI.</p><label>Adresse e-mail<div><Mail/><input type="email" required placeholder="coach@sailmotion.ai"/></div></label><label>Mot de passe<div><LockKeyhole/><input type="password" required minLength={4} placeholder="••••••••"/><Eye/></div></label><div className="login-help"><label><input type="checkbox"/> Se souvenir de moi</label><button type="button" onClick={()=>setStep("forgot")}>Mot de passe oublié ?</button></div><button className="login-submit" type="submit">Se connecter <ArrowRight/></button><button className="demo-login" type="button" onClick={onSubmit}>Accéder au compte de démonstration</button><p className="auth-switch">Pas encore de compte ? <button type="button" onClick={()=>setStep("signup")}>Créer un compte</button></p></form></div>;
}

function Dashboard({ analyses, query, onOpenAnalysis }: { analyses: Analysis[]; query: string; onOpenAnalysis: () => void }) {
  const filtered=useMemo(()=>analyses.filter(a=>`${a.name} ${a.boat}`.toLowerCase().includes(query.toLowerCase())),[analyses,query]);
  return <><section className="stats-grid">{stats.map(([Icon,label,value,note,color])=><article className="stat-card" key={label}><span className={`stat-icon ${color}`}><Icon/></span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></article>)}</section><section className="dashboard-grid">
    <article className="panel performance"><div className="panel-title"><h2>Évolution des scores</h2><button>6 derniers mois <ChevronDown/></button></div><LineChart/><div className="months"><span>Jan</span><span>Fév</span><span>Mar</span><span>Avr</span><span>Mai</span><span>Juin</span><span>Juil</span></div></article>
    <article className="panel distribution"><h2>Répartition des analyses</h2><div className="donut-row"><div className="donut"/><ul><li>Virement <b>28%</b></li><li>Empannage <b>20%</b></li><li>Départ <b>18%</b></li><li>Vent arrière <b>12%</b></li><li>Près <b>10%</b></li></ul></div></article>
    <article className="panel heatmap"><h2>Heatmap Performance</h2><div className="heat-table"><div/><span>Technique</span><span>Vitesse</span><span>Équilibre</span><span>Transitions</span><span>VMG</span>{["Virement","Empannage","Départ","Vent arrière","Près","Portant"].flatMap((r,ri)=>[<b key={r}>{r}</b>,...[0,1,2,3,4].map((_,i)=><i key={`${r}${i}`} className={`h${(ri+i)%5}`}/>)])}</div></article>
    <article className="panel global-score"><h2>Score technique global</h2><ScoreRing/><strong>Excellent</strong><div className="stars">★★★★★</div><ul><li>Technique <b>90/100</b></li><li>Équilibre <b>85/100</b></li><li>Vitesse <b>82/100</b></li><li>VMG <b>87/100</b></li></ul></article>
    <article className="panel recent"><div className="panel-title"><h2>Dernières analyses</h2><button onClick={onOpenAnalysis}>Voir tout ›</button></div>{filtered.map((a,i)=><div className="analysis-row" key={`${a.name}-${i}`}><img src={i%2?"/sailing/catamaran.jpg":"/sailing/laser.jpg"}/><div><strong>{a.name}</strong><small>{a.boat}</small></div><b>{a.score}</b><span>{a.date}</span><button onClick={onOpenAnalysis}>Voir</button></div>)}</article>
    <article className="panel video-card"><h2>Dernière vidéo analysée</h2><div className="video-stage"><img src="/sailing/laser.jpg" alt="Navigation en ILCA 7"/><button onClick={onOpenAnalysis}><Play fill="currentColor"/></button><div className="video-progress"><span/></div></div><div className="video-meta"><div><h3>Virement · ILCA 7</h3><p>23/07/2026 · Rabat, Maroc</p></div><ScoreRing score={88}/></div><button className="report" onClick={onOpenAnalysis}>Voir le rapport</button></article>
    <article className="panel weather"><h2>Conditions météo</h2><div className="weather-grid"><div><Wind/><b>18<small> nds</small></b><span>Vent NNO</span></div><div><Activity/><b>0.8<small> m</small></b><span>Houle</span></div><div><Gauge/><b>24<small>°C</small></b><span>Température</span></div><div><Share2/><b>0.5<small> nds</small></b><span>Courant</span></div></div></article>
    <article className="panel goals"><h2>Objectifs hebdomadaires</h2>{[["Réaliser 5 analyses",100],["Analyser 10 virements",60],["Analyser 20 départs",100],["VMG moyenne > 5.8 nds",82],["Score moyen > 90",87]].map(([l,n])=><div className="goal" key={String(l)}><div><span>{l}</span><b>{n}%</b></div><i><em style={{width:`${n}%`}}/></i></div>)}</article>
  </section></>;
}

function AnalysesPage({ analyses, onCreated }: { analyses: Analysis[]; onCreated: (a: Analysis) => void }) {
  const [showAnalyzer,setShowAnalyzer]=useState(false);
  return <div className="content-page"><div className="page-heading"><div><span className="eyebrow">VISION ARTIFICIELLE</span><h1>Analyses vidéo</h1><p>Importez une vidéo, lancez l’analyse et consultez les résultats techniques.</p></div><button className="primary-page-button" onClick={()=>setShowAnalyzer(true)}><CloudUpload/>Nouvelle analyse</button></div>{showAnalyzer&&<div className="analyzer-wrap"><NavFlowAIAnalyzer sessionId={`analysis-${Date.now()}`}/><button className="save-analysis" onClick={()=>{onCreated({name:"Nouvelle analyse IA",boat:"ILCA / Laser",score:88,date:"À l’instant"});setShowAnalyzer(false)}}>Enregistrer dans mes analyses</button></div>}<div className="analysis-library">{analyses.map((a,i)=><article key={`${a.name}-${i}`}><img src={i%2?"/sailing/catamaran.jpg":"/sailing/laser.jpg"}/><div><span>{a.boat}</span><h3>{a.name}</h3><p>{a.date}</p></div><ScoreRing score={a.score}/><button onClick={()=>setShowAnalyzer(true)}><Play/>Ouvrir</button></article>)}</div></div>;
}

function SectionPage({ title }: { title: string }) {
  const content: Record<string,[string,string,string][]>={"Vidéos":[["Bibliothèque vidéo","214 vidéos disponibles","Gérez vos imports et vos enregistrements."],["Derniers imports","24 cette semaine","Les vidéos sont prêtes pour l’analyse."],["Stockage","38% utilisé","Vos médias restent organisés par session."]],"Athlètes":[["Athlètes actifs","26 profils","Suivez chaque navigateur individuellement."],["Progression moyenne","+12%","Évolution sur les 30 derniers jours."],["Clubs","3 équipes","CNPR Rabat, YCR et CNR."]],"Progression":[["Score actuel","87/100","Votre meilleur résultat cette saison."],["Gain mensuel","+12%","Progression régulière et mesurable."],["Objectif","90/100","Plus que trois points à gagner."]],"IA Coach":[["Conseil du jour","Travaillez la transition","Gardez le regard loin pendant le virement."],["Point fort","Stabilité","Votre contrôle de coque progresse."],["Priorité","Ouverture des épaules","Réduisez la tension durant la rotation."]]};
  const cards=content[title]??[["Module disponible",title,"Cette section est prête pour vos prochaines données."],["Synchronisation","Active","Les données SailMotion AI sont à jour."],["Prochaine étape","Nouvelle analyse","Importez une vidéo pour enrichir cette page."]];
  return <div className="content-page"><div className="page-heading"><div><span className="eyebrow">SAILMOTION AI</span><h1>{title}</h1><p>Consultez et gérez toutes les informations de ce module.</p></div></div><div className="module-grid">{cards.map(([k,v,d],i)=><article key={k}><span className={`stat-icon ${["blue","green","violet"][i]}`}><Activity/></span><small>{k}</small><h2>{v}</h2><p>{d}</p><button>Consulter <ArrowRight/></button></article>)}</div></div>;
}

export default function App(){
  const [screen,setScreen]=useState<"landing"|"login"|"app">("landing"); const[active,setActive]=useState("Tableau de bord"); const[menuOpen,setMenuOpen]=useState(false); const[query,setQuery]=useState(""); const[analyses,setAnalyses]=useState(initialAnalyses);
  if(screen==="landing")return <Landing onLogin={()=>setScreen("login")}/>; if(screen==="login")return <Login onBack={()=>setScreen("landing")} onSubmit={()=>setScreen("app")}/>;
  const openAnalyses=()=>setActive("Analyses");
  return <div className="app-shell"><aside className={`sidebar ${menuOpen?"open":""}`}><button className="close-mobile" onClick={()=>setMenuOpen(false)}><X/></button><NavFlowBrand className="brand"/><nav>{nav.map(([Icon,label])=><button key={label} className={active===label?"active":""} onClick={()=>{setActive(label);setMenuOpen(false)}}><Icon/><span>{label}</span>{label==="IA Coach"&&<em>NOUVEAU</em>}</button>)}</nav><button className="logout" onClick={()=>setScreen("landing")}><LogOut/>Déconnexion</button><div className="sidebar-footer"><img src="/sailing/laser.jpg" alt=""/><div><strong>SAILMOTION <i>AI</i></strong><small>Version 2.1.0</small><small>© 2026 Tous droits réservés</small></div></div></aside><main><header><button className="menu-mobile" onClick={()=>setMenuOpen(true)}><Menu/></button><label className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher une analyse, un athlète, une vidéo..."/></label><div className="header-actions"><button><Bell/><b>3</b></button><button><Moon/></button><button onClick={()=>setActive("Paramètres")}><Settings/></button><span className="avatar">M</span><div className="profile"><strong>Mouad</strong><small>Coach</small></div><ChevronDown/></div></header><section className="topbar"><div><h1>{active}</h1><p>Bonjour Mouad, votre espace de performance est prêt.</p></div><div className="filters"><button><span>Club<small>CNPR Rabat</small></span><ChevronDown/></button><button><span>Rôle<small>Coach</small></span><ChevronDown/></button></div><div className="primary-actions"><button onClick={openAnalyses}><CloudUpload/>Importer vidéo</button><button className="primary" onClick={openAnalyses}>＋ Nouvelle analyse</button><button className="live" onClick={openAnalyses}><Video/>Analyse en direct</button></div></section>{active==="Tableau de bord"?<Dashboard analyses={analyses} query={query} onOpenAnalysis={openAnalyses}/>:active==="Analyses"?<AnalysesPage analyses={analyses} onCreated={a=>setAnalyses(x=>[a,...x])}/>:<SectionPage title={active}/>}</main></div>;
}
